service: serverless-s3-example
provider:
  name: aws
  runtime: nodejs18.x
plugins:
  - serverless-s3
  - serverless-offline
custom:
  # Uncomment only if you want to collaborate with serverless-plugin-additional-stacks
  # additionalStacks:
  #    permanent:
  #      Resources:
  #        S3BucketData:
  #            Type: AWS::S3::Bucket
  #            Properties:
  #                BucketName: ${self:service}-data
  s3:
    host: localhost
    port: 8000
    directory: /tmp
    # Uncomment only if you already have a S3 server running locally
    # noStart: true
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: /
          method: get
  s3hook:
    handler: handler.s3hook
    events:
      - s3:
          bucket: local-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
            - suffix: .jpg
