# from https://dev.to/puku0x/github-actions-1mi5
name: Bump version

on:
 workflow_dispatch:
  inputs:
    bumpTarget:
      description: 'bump target major/minor/patch'
      required: true
      default: 'patch'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Switch branch
        run: git switch -c tmp
      - name: Git config
        run: |
          git config --local user.email "machineuser+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Get branch
        id: get_branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Bump version
        id: bump_version
        run: |
          pushd  serverless-s3
          version=$(npm version ${{ github.event.inputs.bumpTarget }} --no-workspaces-update | tail -n 1)
          echo ::set-output name=VERSION::${version}
          popd
      - name: Commit pyproject.toml
        id: commit_pyproject_toml
        run: |
          git add serverless-s3/package.json
          git commit -m "chore(*): bump version to ${VERSION}"
        env:
          VERSION: ${{ steps.bump_version.outputs.VERSION }}
      - name: Push branch
        run: |
          git branch -m bump-${VERSION}
          git push -u origin bump-${VERSION}
        env:
          VERSION: ${{ steps.bump_version.outputs.VERSION }}
      - name: Create pull request
        uses: actions/github-script@v7
        env:
          BRANCH: ${{ steps.get_branch.outputs.BRANCH }}
          VERSION: ${{ steps.bump_version.outputs.VERSION }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'chore(*): bump ' + process.env.VERSION,
              head: context.repo.owner + ':' + 'bump-' + process.env.VERSION,
              base: process.env.BRANCH,
              body: ''
            })
