# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches-ignore:
      - 'bump-v*'
    tags-ignore:
      - v*


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: install
        run: |
          npm install

      - name: test put_with_s3_event_response
        run: |
          ./example/test-example.sh put_with_s3_event_response

      - name: test resize_image
        run: |
          ./example/test-example.sh resize_image

      - name: test simple_event
        run: |
          ./example/test-example.sh simple_event

      - name: test simple_event_python
        run: |
          ./example/test-example.sh simple_event_python

      - name: test simple_put
        run: |
          ./example/test-example.sh simple_put

      - name: test webpack_support
        run: |
          ./example/test-example.sh webpack_support